es.tr

I have not changed some of the lines, like 'The V Programming Language' and some words like 'Strings', as I think should stay in english.

Add spanish translation

---

de.tr

I also removed unnecessary white space.

Fixes and changes to the German translation

---

ko.tr

This PR includes the translation of Korean.
Signed-off-by: Ji-Hyeon Gim <potatogim@potatogim.net>

Add Korean Translation

---

pt-br.tr

First general translation to Portuguese Brazilian

Add Brazilian Portuguese translation

---

uk.tr

Translated for Ukrainian language.

Ukraine translation.

---

fr.tr

Updated the French translation file to the latest keys (taken in the en.tr file)

Updated fr translation

---

docs.html

update match & defer docs

---

docs.html

Mention compile time if with `debug`

Mention compile time if with `debug`

---

docs.html

minor change in the ORM sample, use := instead of =
to avoid compile error

fix syntax error orm sample

---

docs.html

minor typo (fix #71)

---

docs.html

Add required `import json`

---

docs.html

little typo error

---

docs.html

Fix docs. Use [].repeat() insted of [;]
Fix typo on the same line as referred in #85

fix: use [].repeat() in docs

---

docs.html

Just some description of the new mod.init() functionality, based on the discord chats so far.

A description of the mod_init functions

---

play.html

play.html: Color.str() now public

---

docs.html

Document the available V options for debugging v programs which use C code.

Expand on the #flag and C interoperability section.

---

index.html

Updated the "Built in ORM" example to current syntax.

fix ORM example

---

index.html

`.now.sh` URLs have been replaced and redirected to `.vercel.app` 😄 
https://v-wasm.vercel.app/

Replace .now.sh with .vercel.app

---

index.html

Fixed a minor typo in the filter-log example.

Fix a very small typo

---

index.html

This results in the removal of that annoying side-scroll.

Fixes Veasel's position on mobile.

---

index.html

I beheaded that vile miscreant.

Makes it impossible for veasel to cause side-scroll

---

compare.html

The old code seems to be from 2-3 years ago and doesn't work with the latest version I tried.
I used what I'v learned so far from the docs, don't know if there is a better/easier way.
I tried to inherit the variables(ids, cursor) from the anonymous function, but didn't work. Also saw some errors and messages that I should report them as bugs.

Update V's code in compare page

---

norwegian.tr

All translations are correct, but can in almost every case be expressed in ten different ways.
This translation offers correct representation of the original material.

+ Add Norwegian localisation norwegian.tr

---

bosnian.tr

Implemented translation for Bosnian language

Bosnian translation

---

french.tr

I just added an entry for french speakers as it was missing

Adding french entry

---

app.css
index.html

Changes latest news text from this:
To:
As requested by @medvednikov 👍

Center latest news text

---

index.html
preview.html

Change **Don** (Logo Contributor) Github Link from https://github.com/donnisnoni to https://github.com/dhonx

Change Don Github Link (Logo Contributor)

---

app.css

Every icon has now the exact same width and all of them fill the space better with a flexbox.
Fixed cursor property in svg

Adjusted landing social icons position
